# Generated by Django 5.1.5 on 2025-03-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='test',
        ),
    ]
