# Generated by Django 5.1.5 on 2025-03-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='test',
        ),
    ]
